services:
  postgres:
    image: postgres:18-alpine
    container_name: vsatemplate-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vsatemplate_postgres_data:/var/lib/postgresql

  seq:
    image: datalust/seq:latest
    container_name: vsatemplate-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_PASSWORD: ${SEQ_PASSWORD}
    ports:
      - "${SEQ_PORT}:80"
    volumes:
      - seq_data:/data

volumes:
  vsatemplate_postgres_data:
  seq_data:  
